export const HOTEL_FILTERS = {
  propertyTypes: [
    "Hotel",
    "Resort",
    "Villa",
    "Apartment",
    "Guest House",
    "Hostel",
    "Homestay",
    "Boutique Hotel",
    "Holiday Park",
    "Luxury Tent",
  ],

  travelGroups: [
    "Family Friendly",
    "Couple Friendly",
    "Adults Only",
    "Pet Friendly",
    "Business Travelers",
    "Solo Travelers",
    "Groups",
  ],

  propertyRating: [
    "5 Star",
    "4 Star",
    "3 Star",
    "2 Star",
    "1 Star",
  ],

  popularFilters: [
    "Breakfast Included",
    "Free Cancellation",
    "Beach Access",
    "Swimming Pool",
    "Free Parking",
    "Spa",
    "Gym",
    "Airport Shuttle",
  ],

  facilities: [
    "Free WiFi",
    "Swimming Pool",
    "Spa",
    "Gym",
    "Free Parking",
    "Restaurant",
    "Bar",
    "Room Service",
    "Airport Shuttle",
    "Business Center",
    "24 Hour Front Desk",
    "Laundry Service",
    "Elevator",
    "Conference Room",
  ],

  roomFacilities: [
    "Air Conditioning",
    "Private Bathroom",
    "Balcony",
    "Sea View",
    "City View",
    "Flat Screen TV",
    "Mini Bar",
    "Coffee Machine",
    "Kitchenette",
    "Bathtub",
    "Hot Tub / Jacuzzi",
    "Non Smoking Rooms",
    "Family Rooms",
    "Mountains View",
  ],

  meals: [
    "Breakfast Included",
    "Half Board",
    "Full Board",
    "All Inclusive",
  ],
};